name: Renovate
# Controls when the workflow will run
on:
  schedule:
    - cron: '0 0/2 * * MON-FRI'

jobs:
  # This workflow contains a single job called "rennovate"
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.0.2
      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v32.52.1
        with:
          configurationFile: .github/renovate.json
          token: ${{ secrets.RENOVATE_TOKEN }}
        env:
          LOG_LEVEL: 'debug'
